name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-fcitx5:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          C:/msys64/usr/bin/pacman -Syu --noconfirm
          C:/msys64/usr/bin/pacman -S --noconfirm `
            mingw-w64-ucrt-x86_64-extra-cmake-modules `
            cmake `
            fmt `
            gcc `
            gettext-devel `
            libuv-devel `
            msys2-runtime-devel `
            ninja
          cp -r its C:/msys64/usr/share/gettext
          Add-Content $env:GITHUB_PATH "C:/msys64/usr/bin"

      - name: Build
        run: |
          cmake -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3

  build-win32:
    runs-on: windows-2025
    defaults:
      run:
        working-directory: win32
    steps:
      - name: Disable CRLF
        working-directory: .
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - name: Lint
        run: ./scripts/lint.ps1

      - name: Build
        run: |
          cmake -B build -G Ninja `
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Test
        run: ctest --test-dir build --output-on-failure

      - name: Check validity
        run: md5sum -c checksum

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
